---
# file: roles/oracle-jdk7-centos/tasks/main.yml
# Configure Oracle JDK common settings.
#

- name: precondition - jdk_version
  fail: msg="ERROR - required variable 'jdk_version' missing."
  when: jdk_version is not defined




- name: check if Oracle JDK 1.7 is installed?
  action: script ../files/check-oracle-jdk7-version.sh
  register: jdk_info

- include: install-jdk.yml
  when: jdk_info.stdout < jdk_version



- name: update /etc/alternatives settings
  sudo: True
  action: script ../files/update-alternatives.sh $jdk_version



#
# install JNA, as recommended by DataStax's Cassandra installation guide
# @see http://www.datastax.com/documentation/cassandra/1.2/index.html#cassandra/install/installRHEL_t.html?pagename=docs&version=1.2&file=install/install_rpm
# @see https://github.com/twall/jna
#

#- name: install JNA (Java Native Access) for better performance
#  sudo: True
#  action: get_url url=https://github.com/twall/jna/blob/3.5.2/dist/jna.jar?raw=true  dest=/usr/share/java/jna.jar

#- name: install JNA (Java Native Access) for better performance
#  sudo: True
#  action: get_url url=https://github.com/twall/jna/blob/3.5.2/dist/platform.jar?raw=true  dest=/usr/share/java/platform.jar



#- name: install JNA (Java Native Access) for better performance
#  sudo: True
#  yum: pkg=jna state=present
#  tags: packages

