---
# file: roles/oracle-jdk7-debian/tasks/main.yml
# Install Oracle JDK 1.7 on Debian.
#
# Adapted from: http://www.webupd8.org/2012/06/how-to-install-oracle-java-7-in-debian.html
# See also: http://d.stavrovski.net/blog/post/installing-oracle-java-7-on-debian-wheezy
#


- name: command to automatically accept the Oracle license
  sudo: True
  shell: echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections

- name: install JDK 7
  sudo: True
  apt: pkg=oracle-java7-installer state=present

- name: set this as default Java; also environment variables
  sudo: True
  apt: pkg=oracle-java7-set-default state=present
