---
# file: roles/disable-remote-root-login/tasks/main.yml
# Configure server: disable root from remote login
#
# USE WITH CAUTION!!!
#
# @see https://blog.nop.im/entries/ansible
# @see https://github.com/pvillega/ansible-ec2-play/blob/master/bootstrap.yaml
#

- name: Disallow root SSH access
  sudo: True
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present

- name: restart ssh service
  sudo: True
  action: service name=sshd state=restarted enabled=yes
