---
# file: roles/mongodb/tasks/main.yml
# Configure MongoDB directly from mongodb.com official repository
#
#

- name: install MongoDB
  sudo: True
  apt: pkg=mongodb-10gen state=present
  when: ansible_os_family == "Debian"
