---
# file: site-web.yml
# playbook for web tier
#

- hosts: all

  vars_files:
    #- group_vars/role-nginx
    #- group_vars/role-redis
    - group_vars/role-oracle-jdk7
    - group_vars/role-ant
    - group_vars/role-mariadb
    #- group_vars/role-cassandra-ring
    #- group_vars/role-cassandra-single

  roles:
    - common
    #- nginx
    - nodejs
    #- redis
    - oracle-jdk7
    - ant
    - mariadb
    #- cassandra

