---
# file: create-app-deployer.yml
# Create server account: add deployment user with sudo rights
#
#
# For security reason, the parameter isn't hard-coded into SCM;
# please specify it manually, e.g., typical command line usage:
#
#   [Case 1] invoked as root:
#
#      % ansible-playbook            \
#          -i [INVENTORY_FILENAME]   \
#          -u root -k -vvv   ZZZ.yml
#
#   [Case 2] invoked as wheel user (without sudo password):
#
#      % ansible-playbook            \
#          -i [INVENTORY_FILENAME]   \
#          -u WWW -k -vvv   ZZZ.yml
#
#   [Case 3] invoked as wheel user (with sudo password):
#
#      % ansible-playbook            \
#          -i [INVENTORY_FILENAME]   \
#          -u WWW -k  --ask-sudo-pass  -vvv   ZZZ.yml
#
#
# @see https://blog.nop.im/entries/ansible
#

- hosts: all

  vars_prompt:
    - name: "APP_DEPLOYER"
      prompt: "INPUT account name for app deployer"
      private: no

    - name: "APP_DEPLOYER_PASSWORD"
      prompt: "INPUT password for app deployer"
      #private: yes
      private: no

  roles:
    - create-app-deployer

