---
# file: disable-remote-root-login.yml
# Bootstrap server: disable remote root login.
# USE WITH CAUTION!!!
#
#
# Typical command line usage:
#
#   [Case 1] invoked as root:
#
#      % ansible-playbook            \
#          -i [INVENTORY_FILENAME]   \
#          -u root -k -vvv   ZZZ.yml
#
#   [Case 2] invoked as wheel user (without sudo password):
#
#      % ansible-playbook            \
#          -i [INVENTORY_FILENAME]   \
#          -u WWW -k -vvv   ZZZ.yml
#
#   [Case 3] invoked as wheel user (with sudo password):
#
#      % ansible-playbook            \
#          -i [INVENTORY_FILENAME]   \
#          -u WWW -k  --ask-sudo-pass  -vvv   ZZZ.yml
#
#
#

- hosts: all
  roles:
    - disable-remote-root-login

