---
# file: roles/nodejs/tasks/main.yml
# Configure node.js common settings.
#

- name: precondition - nodejs_version
  fail: msg="ERROR - required variable 'nodejs_version' missing."
  when: nodejs_version is not defined
 


- name: install NVM (Node.js Version Manager)
  sudo: True
  shell: creates={{ nvm_exe_path }}  curl -sSL https://raw.githubusercontent.com/creationix/nvm/master/install.sh | NVM_DIR={{ nodejs_install_path }}  bash

- name: activate NVM for all users
  sudo: True
  template: src=../templates/activate-nvm.sh.j2  dest=/etc/profile.d/activate-nvm.sh  owner=root group=root mode=755

- name: apply nvm.sh and set default version
  sudo: True
  shell: /bin/bash -c "source {{ nvm_exe_path }}  &&  nvm install {{ nodejs_version }}  &&  nvm use {{ nodejs_version }}  &&  nvm alias default {{ nodejs_version }}"

