---
# file: roles/common/tasks/centos6_x64-time.yml
# Configure CentOS time-related settings.
#
# @see https://coderwall.com/p/hdul2g
#
# tags: time ntp
#

- name: set time zone to given $timezone
  sudo: True
  action: command cp -p /usr/share/zoneinfo/{{timezone}}  /etc/localtime 
  when: timezone is defined
  tags: time

- name: set time zone to GMT+8
  sudo: True
  action: command cp -p /usr/share/zoneinfo/Asia/Taipei /etc/localtime
  when: timezone is not defined
  tags: time

- name: be sure ntp is installed
  sudo: True
  yum: pkg=ntp state=installed
  tags: time ntp packages

- name: be sure ntpd is running and enabled
  sudo: True
  service: name=ntpd state=started enabled=yes
  tags: time ntp packages

