---
# file: roles/common/tasks/debian-apt.yml
# Configure Debian/Ubuntu apt system.
#
#
# tags: packages
#


- name: Import WebUpd8 PGP key
  sudo: True
  command: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886

- name: add the WebUpd8 Oracle Java PPA repository
  sudo: True
  shell: echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu precise main"     | tee /etc/apt/sources.list.d/webupd8team-java.list

- name: add the WebUpd8 Oracle Java PPA repository
  sudo: True
  shell: echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu precise main" | tee -a /etc/apt/sources.list.d/webupd8team-java.list




- name: Import MongoDB PGP key
  sudo: True
  command: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7F0CEB10

- name: add the MongoDB PPA repository
  sudo: True
  shell: echo "deb http://downloads-distro.mongodb.org/repo/debian-sysvinit dist 10gen" | tee /etc/apt/sources.list.d/mongodb.list





- name: Run the equivalent of "apt-get update" as a separate step
  sudo: True
  apt: update_cache=yes
  when: ansible_pkg_mgr == "apt"
  tags: packages
