---
# file: roles/common/tasks/disable-services.yml
# Configure Linux: disable unused services.
#
# @see http://www.weithenn.org/cgi-bin/wiki.pl?CentOS_5.x-%E5%88%9D%E5%A7%8B%E7%92%B0%E5%A2%83%E8%A8%AD%E5%AE%9A
#
# tags:
#



- name: stop unused services, if any (for CentOS)
  sudo: True
  service: name={{ item }}  state=stopped
  ignore_errors: true
  when: ansible_pkg_mgr == "yum"
  with_items:
    - acpid
    - atd
    - cpuspeed
    - ip6tables
    - messagebus

- name: stop unused services, if any (for Debian/Ubuntu)
  sudo: True
  command: /usr/sbin/invoke-rc.d {{ item }}  stop
  ignore_errors: true
  when: ansible_pkg_mgr == "apt"
  with_items:
    - acpid
    - atd



- name: turn off unused services (for CentOS)
  sudo: True
  shell: chkconfig  {{ item }}  off
  ignore_errors: true
  when: ansible_pkg_mgr == "yum"
  with_items:
    - acpid
    - atd
    - cpuspeed
    - ip6tables
    - messagebus

- name: turn off unused services (for Debian/Ubuntu)
  sudo: True
  command: /usr/sbin/update-rc.d  {{ item }}  disable
  ignore_errors: true
  when: ansible_pkg_mgr == "apt"
  with_items:
    - acpid
    - atd


