---
# file: roles/common/tasks/limit.yml
# Configure Linux resource limits.
#
# @see "Recommended production settings" provided by DataStax Cassandra:
#      http://www.datastax.com/documentation/cassandra/1.2/index.html#cassandra/install/installRecommendSettings.html
#
#

- name: precondition - ulimit
  fail: msg="ERROR - required variable 'ulimit' missing."
  when: ulimit is not defined


- name: comment out "bridge" sysctl to avoid error
  sudo: True
  lineinfile: dest=/etc/sysctl.conf regexp='^net.bridge.bridge-nf-call-ip6tables' line='#net.bridge.bridge-nf-call-ip6tables = 0' state=present

- name: comment out "bridge" sysctl to avoid error
  sudo: True
  lineinfile: dest=/etc/sysctl.conf regexp='^net.bridge.bridge-nf-call-iptables' line='#net.bridge.bridge-nf-call-iptables = 0' state=present

- name: comment out "bridge" sysctl to avoid error
  sudo: True
  lineinfile: dest=/etc/sysctl.conf regexp='^net.bridge.bridge-nf-call-arptables' line='#net.bridge.bridge-nf-call-arptables = 0' state=present


- name: maximum File Descriptors (FD) enforced on a kernel level
  # @see http://serverfault.com/questions/122679/how-do-ulimit-n-and-proc-sys-fs-file-max-differ
  sudo: True
  action: sysctl name=fs.file-max value=999999 state=present
  #action: sysctl name=fs.file-max value=813893 state=present


- name: set ulimit -n
  sudo: True
  action: shell ulimit -n {{ulimit}}

- name: save to /etc/security/limits.conf permanently
  sudo: True
  action: template src=../templates/limits.conf.j2 dest=/etc/security/limits.conf owner=root group=root mode=0644 backup=yes


- name: max number of memory map areas a process may have
  sudo: True
  action: sysctl name=vm.max_map_count value=131072 state=present


- name: increase the number of user's processes
  sudo: True
  action: lineinfile dest=/etc/security/limits.d/90-nproc.conf regexp='^\*\s+soft' line='*          soft    nproc     10240' state=present backup=yes
  when: ansible_pkg_mgr == "yum"


#
# TCP/IP settings
#

- name: Increase system IP port limits to allow for more connections
  sudo: True
  action: sysctl name=net.ipv4.ip_local_port_range value="1024 65000" state=present


- name: time for FIN-WAIT-2 -> TIME_WAIT
  sudo: True
  action: sysctl name=net.ipv4.tcp_fin_timeout value=20 state=present


- name: the number of unacknowledged probes to send before considering the connection dead and notifying the application layer
  sudo: True
  action: sysctl name=net.ipv4.tcp_keepalive_probes value=5 state=present


- name: the interval between subsequential keepalive probes
  sudo: True
  action: sysctl name=net.ipv4.tcp_keepalive_intvl value=30 state=present


- name: allows reusing sockets in TIME_WAIT state for new connections when it is safe from protocol viewpoint
  sudo: True
  action: sysctl name=net.ipv4.tcp_tw_reuse value=1 state=present


#- name: enables fast recycling of TIME_WAIT sockets
#        @see http://stackoverflow.com/questions/6426253/tcp-tw-reuse-vs-tcp-tw-recycle-which-to-use-or-both
#  sudo: True
#  action: sysctl name=net.ipv4.net.ipv4.tcp_tw_recycle value=1 state=present


- name: increase the receive window size above its former maximum value of 65,535 bytes.
  sudo: True
  sysctl: name=net.ipv4.tcp_window_scaling  value=1 state=present


- name: number of packets to keep in backlog before the kernel starts dropping
  sudo: True
  sysctl: name=net.ipv4.tcp_max_syn_backlog  value=3240000  state=present


- name: increase socket listen backlog
  sudo: True
  sysctl: name=net.core.somaxconn value=3240000 state=present
  sysctl: name=net.ipv4.tcp_max_tw_buckets value=1440000 state=present


#
# Increase TCP buffer sizes
#

- name: Increase TCP buffer sizes
  sudo: True
  sysctl: name=net.core.rmem_default value=8388608   state=present
  sysctl: name=net.core.rmem_max     value=16777216  state=present
  sysctl: name=net.core.wmem_max     value=16777216  state=present
  sysctl: name=net.ipv4.tcp_rmem     value="4096 4096 25165824"  state=present
  sysctl: name=net.ipv4.tcp_wmem     value="4096 4096 25165824"  state=present
  sysctl: name=net.ipv4.tcp_congestion_control  value=cubic  state=present

