---
# file: roles/common/tasks/main.yml
# Configure common settings for Linux operating systems.
#

- include: time.yml
- include: limit.yml

- include: debian-locale.yml
  when: ansible_pkg_mgr == "apt"



- include: centos6_x64-yum.yml
  when: ansible_os_family == "CentOS"

- include: debian-apt.yml
  when: ansible_pkg_mgr == "apt"





- include: disable-services.yml

###- include: centos6_x64-sudo.yml
###  when: ansible_os_family == "CentOS"






- include: maintenance.yml
- include: tools.yml
- include: perl.yml
- include: python.yml
- include: monitors.yml

- include: benchmark.yml
