---
# file: roles/common/tasks/maintenance.yml
# Configure useful maintenance tools.
#
# [MEMO] CentOS 6 and Debian 7 already has logrotate installed by default!
#
# tags: packages maintenance
#


#
# LVM (Linux Volume Manager) - userland logical volume management tools
#

- name: install lvm2
  sudo: True
  yum: name=lvm2 state=present
  when: ansible_pkg_mgr == "yum"
  tags: packages maintenance

- name: install lvm2
  sudo: True
  apt: pkg=lvm2 state=present
  when: ansible_pkg_mgr == "apt"
  tags: packages maintenance



#
# log maintenance tools
#

- name: install logrotate
  sudo: True
  yum: name=logrotate state=present
  when: ansible_pkg_mgr == "yum"
  tags: packages maintenance

- name: install logrotate
  sudo: True
  apt: pkg=logrotate state=present
  when: ansible_pkg_mgr == "apt"
  tags: packages maintenance



- name: set directory permission
  sudo: True
  file: dest=/etc/logrotate.d mode=755 state=directory owner=root group=root

- name: copy default logrotate conf file (timestamp=200708291519.36)
  sudo: True
  copy: src=../files/logrotate.conf  dest=/etc/ owner=root group=root mode=0644


#
# chkconfig-like UI utils for Debian/Ubuntu
#

- name: install sysv-rc-conf
  sudo: True
  apt: pkg=sysv-rc-conf state=present
  when: ansible_pkg_mgr == "apt"
  tags: packages maintenance



#
# diagnosis tools
#

- name: install htop
  sudo: True
  yum: name=htop state=present
  when: ansible_pkg_mgr == "yum"
  tags: packages maintenance

- name: install htop
  sudo: True
  apt: pkg=htop state=present
  when: ansible_pkg_mgr == "apt"
  tags: packages maintenance

