---
# file: roles/common/tasks/monitors.yml
# Configure CentOS useful tools for monitoring daemon services.
#
# tags: packages monitor
#


#
# monitoring tools
#

- name: install upstart
  sudo: True
  yum: pkg=upstart state=installed
  tags: packages monitor

#- name: install monit
#  sudo: True
#  yum: pkg=monit state=installed
#  tags: packages monitor

