---
# file: roles/common/tasks/monitors.yml
# Configure useful tools for monitoring daemon services.
#
# tags: packages monitor
#


#
# monitoring tools
#

#- name: install upstart
#  sudo: True
#  yum: pkg=upstart state=installed
#  tags: packages monitor


- name: install monit
  sudo: True
  yum: name=monit state=present
  when: ansible_pkg_mgr == "yum"
  tags: packages monitor

- name: install monit
  sudo: True
  apt: pkg=monit state=present
  when: ansible_pkg_mgr == "apt"
  tags: packages monitor



- name: default conf for monit
  sudo: True
  copy: src=../files/monit.DEFAULT dest=/etc/monit.d/DEFAULT owner=root group=root mode=0644
  tags: packages monitor

- name: logrotate for monit
  sudo: True
  copy: src=../files/monit.logrotate dest=/etc/logrotate.d/monit owner=root group=root mode=0644
  tags: packages monitor

- name: enable monit service
  sudo: True
  service: name=monit state=started enabled=yes
  tags: packages monitor


#
# install Runit via pre-generated RPM
# @see https://github.com/imeyer/runit-rpm
#
#- name: install Runit
#  sudo: True


