---
# file: roles/common/tasks/perl.yml
# Configure Perl basic tools.
#
# tags: packages perl
#

- name: install Perl, if necessary
  sudo: True
  yum: name=perl state=present
  when: ansible_pkg_mgr == "yum"
  tags: packages perl

- name: install Perl, if necessary
  sudo: True
  apt: pkg=perl state=present
  when: ansible_pkg_mgr == "apt"
  tags: packages perl



- name: install core Perl modules (for Debian)
  sudo: True
  apt: pkg=perl-modules state=present
  when: ansible_pkg_mgr == "apt"
  tags: packages perl

- name: install CPAN (for CentOS)
  sudo: True
  yum: pkg=perl-CPAN state=present
  when: ansible_pkg_mgr == "yum"
  tags: packages perl


