---
# file: roles/common/tasks/python.yml
# Configure Python basic tools.
#
# tags: packages python
#

- name: install Python, if necessary
  sudo: True
  yum: name=python state=present
  when: ansible_pkg_mgr == "yum"
  tags: packages python

- name: install Python, if necessary
  sudo: True
  apt: pkg=python state=present
  when: ansible_pkg_mgr == "apt"
  tags: packages python



- name: install easy_install
  sudo: True
  yum: name=python-setuptools state=present
  when: ansible_pkg_mgr == "yum"
  tags: packages python

- name: install easy_install
  sudo: True
  apt: pkg=python-setuptools state=present
  when: ansible_pkg_mgr == "apt"
  tags: packages python



- name: install pip (by easy_install)
  sudo: True
  easy_install: name=pip
  when: ansible_pkg_mgr == "yum"
  tags: packages python

- name: install pip (for Debian/Ubuntu)
  sudo: True
  apt: pkg=python-pip state=present
  when: ansible_pkg_mgr == "apt"
  tags: packages python



