---
# file: roles/ant/tasks/main.yml
# Configure Ant common settings.
#

- name: precondition - ant_version
  fail: msg="ERROR - required variable 'ant_version' missing."
  when: ant_version is not defined

- name: be sure Ant is never installed previously by yum
  sudo: True
  yum: pkg=ant state=absent
  tags: packages




- name: check if Ant is installed?
  action: script ../files/check-ant-version.sh
  register: ant_info

- include: install-ant.yml
  when: ant_info.stdout < ant_version

